name: Go

on:
  push:
    branches: [ master ]

jobs:
  lint:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27

  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - uses: actions/checkout@v2

      - name: Test
        run: go test -v ./...
